services:
  minecraft-server:
    environment:
      EULA: 'true'
      TYPE: AUTO_CURSEFORGE
      CF_IGNORE_MISSING_FILES: |
         mods/iris-*.jar
         mods/sodium-*.jar
         mods/figura-*.jar
      MEMORY: 15G
      ENABLE_COMMAND_BLOCK: 'TRUE'
    image: itzg/minecraft-server
    ports:
    - 25565:25565
    volumes:
    - ./data:/data
    - ./downloads:/downloads:rw
