services:
  minecraft-server:
    environment:
      EULA: 'true'
      TYPE: AUTO_CURSEFORGE
      CF_IGNORE_MISSING_FILES: |
        mods/iris-*.jar
        mods/sodium-*.jar
        mods/figura-*.jar
      entrypoint: ["sudo","rm", "-rf", "mods/iris-*", "mods/sodium-*", "mods/figura*"]
      MEMORY: 15G
    image: itzg/minecraft-server
    ports:
    - 25565:25565
    volumes:
    - ./data:/data
    - ./downloads:/downloads:rw
